#!/bin/bash
set -e

SSL_CERT="$PG_SSL_DIR/server.crt"
SSL_KEY="$PG_SSL_DIR/server.key"

init_certs() {
	mkdir -p $PG_SSL_DIR
	openssl req -new -x509 -days 365 -nodes -newkey ec:<(openssl ecparam -name prime256v1) \
		-keyout "$SSL_KEY" -out "$SSL_CERT" -subj "/CN=postgres"
	chmod 600 "$SSL_KEY"
	chown postgres:postgres "$SSL_CERT" "$SSL_KEY"
}

if [ ! -f "$SSL_CERT" ]; then
	echo "Generating SSL certificatess..."
	init_certs
elif ! openssl x509 -noout -text -in "$SSL_CERT" | grep -q "DNS:postgres"; then
	echo "Existing certificate wasn't generated by us. Regenerating..."
	init_certs
elif ! openssl x509 -checkend 2592000 -noout -in "$SSL_CERT"; then
	echo "Existing certificate expires soon. Regenerating..."
	init_certs
fi

unset PGHOST
unset PGPORT

exec docker-entrypoint.sh postgres \
	-c ssl=on \
	-c ssl_cert_file="$SSL_CERT" \
	-c ssl_key_file="$SSL_KEY" \
	-c listen_addresses=*
	"$@"
